import React from 'react';
import '../css/Buttons.css';

function Buttons() {

  return(
    <section>  
      <div className="container1">
        <button
          value="7"
          onClick=""
        >
          7
        </button>
        <button
          value="8"
          onClick=""
        >
          8
        </button>
        <button
          value="9"
          onClick=""
        >
          9
        </button>
        <button
          value="/"
          onClick=""
        >
          /
        </button>
        <button
          onClick=""
        >
          voltar
        </button>
        <button
          onClick=""
        >
          C
        </button>
      </div>
      <div className="container2">
        <button
          value="4"
          onClick=""
        >
          4
        </button>
        <button
          value="5"
          onClick=""
        >
          5
        </button>
        <button
          value="6"
          onClick=""
        >
          6
        </button>
        <button
          value="*"
          onClick=""
        >
          x
        </button>
        <button
          value="("
          onClick=""
        >
          (
        </button>
        <button
          value=")"
          onClick=""
        >
          )
        </button>
      </div>
      <div className="container3">
        <button
          value="1"
          onClick=""
        >
          1
        </button>
        <button
          value="2"
          onClick=""
        >
          2
        </button>
        <button
          value="3"
          onClick=""
        >
          3
        </button>
        <button
          value="-"
          onClick=""
        >
          -
        </button>
        <button
          value=""
          onClick=""
        >
          x^2
        </button>
        <button
          value=""
          onClick=""
        >
          V
        </button>
      </div>
      <div className="container4">
        <button
          value="0"
          onClick=""
        >
          0
        </button>
        <button
          value="."
          onClick=""
        >
          ,
        </button>
        <button
          value=""
          onClick=""
        >
          %
        </button>
        <button
          value="+"
          onClick=""
        >
          +
        </button>
        <button
          id="result"
          value="="
          onClick=""
        >
          =
        </button>
      </div>
    </section>
  );
}

export default Buttons;
