import React from 'react';
import '../css/Buttons.css';

function Buttons() {

  return(
    <section>  
      <div className="container1">
        <button
          value=""
          onClick=""
        >
          7
        </button>
        <button
          value=""
          onClick=""
        >
          8
        </button>
        <button
          value=""
          onClick=""
        >
          9
        </button>
        <button
          value=""
          onClick=""
        >
          /
        </button>
        <button
          value=""
          onClick=""
        >
          voltar
        </button>
        <button
          value=""
          onClick=""
        >
          C
        </button>
      </div>
      <div className="container2">
        <button
          value=""
          onClick=""
        >
          4
        </button>
        <button
          value=""
          onClick=""
        >
          5
        </button>
        <button
          value=""
          onClick=""
        >
          6
        </button>
        <button
          value=""
          onClick=""
        >
          x
        </button>
        <button
          value=""
          onClick=""
        >
          (
        </button>
        <button
          value=""
          onClick=""
        >
          )
        </button>
      </div>
      <div className="container3">
        <button
          value=""
          onClick=""
        >
          1
        </button>
        <button
          value=""
          onClick=""
        >
          2
        </button>
        <button
          value=""
          onClick=""
        >
          3
        </button>
        <button
          value=""
          onClick=""
        >
          -
        </button>
        <button
          value=""
          onClick=""
        >
          x^2
        </button>
        <button
          value=""
          onClick=""
        >
          V
        </button>
      </div>
      <div className="container4">
        <button
          value=""
          onClick=""
        >
          0
        </button>
        <button
          value=""
          onClick=""
        >
          ,
        </button>
        <button
          value=""
          onClick=""
        >
          %
        </button>
        <button
          value=""
          onClick=""
        >
          +
        </button>
        <button
          value=""
          onClick=""
        >
          =
        </button>
      </div>
    </section>
  );
}

export default Buttons;
